// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fmtmyhqcabsjgezbisqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtdG15aHFjYWJzamdlemJpc3F6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNTI5NjcsImV4cCI6MjA1OTkyODk2N30.h5wVs8PUytOfQq2CvJX-Ti9qAORrgyKXYoTdH43jf3s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);